apiVersion: v1
kind: Pod
metadata:
  name: devops_exercise
  labels:
    app: python
spec:
  containers:
    - name: devops_exercise
      image: tachomi/devops_exercise
      ports:
        - containerPort: 5000
